[font]
    size = 10

[font.normal]
    family = "SauceCodePro Nerd Font Mono"
    style = "Regular"
[font.bold]
    family = "SauceCodePro Nerd Font Mono"
    style = "Bold"
[font.bold_italic]
    family = "SauceCodePro Nerd Font Mono"
    style = "Bold Italic"
[font.italic]
    family = "SauceCodePro Nerd Font Mono"
    style = "Italic"

[window]
    # decorations="None" # Nice, but can't really move the window as easily
    dynamic_title = true
    decorations_theme_variant = "Dark"

[bell] # Defaults, but just in case
    duration = 0
    command = "None"

    # This is great for windows, but breaks stuff if I try using the same config for Linux
    # [terminal.shell]
    #     program = "pwsh"
    #     args = [ # Open to ~ if it tries going to the root dir, but go where it wants otherwise (Context menu > open here)
    #         "-NoExit",
    #         "-Command",
    #         "if ($PWD.Path -like '*System32*') { Set-Location ~ }",
    #     ]

[terminal]
    osc52 = "CopyPaste" # Helps with clipboard operations

[general]
    live_config_reload = true
    working_directory = "None"

[env]
    TERM = "xterm-256color"

[keyboard]
    bindings = [
        { key = "Slash", mods = "Control", chars = "\u001f" }, # Ctrl+/     (Nvim comment)
        { key = "Space", mods = "Control", chars = "\u0000" }, # Ctrl+Space (Tmux prefix)
        { key = "End", mods = "None", chars = "\u001b[F" },    # End key
        { key = "Home", mods = "None", chars = "\u001b[H" },   # End key
	{ key = "Return", mods = "Shift", chars = "\u001b\r"},   # Shift-Enter for line return on claude
    ]

[cursor]
    unfocused_hollow = true
[cursor.style]
    blinking = "Never"

[colors.primary]
    background = "#000000"
    foreground = "#DDDDDD"
[colors.cursor]
    text = "#000000"
    cursor = "#00FF00"
[colors.normal]
    black = "#000000"
    red = "#BB0000"
    green = "#00FF00"
    yellow = "#f6fa00"
    blue = "#233eeb"
    magenta = "#BB00BB"
    cyan = "#00FFFF"
    white = "#DDDDDD"
[colors.bright]
    black = "#444444"
    red = "#FF5555"
    green = "#00BB00"
    yellow = "#f6fa00"
    blue = "#5555FF"
    magenta = "#FF55FF"
    cyan = "#00BBBB"
    white = "#FFFFFF"


